### ISSUE TITLE
bug: error in `secp256k1_add` when adding point at infinity

### ISSUE THREAD

**Issue by enitrat** [lambdaclass/cairo_native#817]
```
thread 'stPreCompiledContracts2::test_CallEcrecover_Overflow_d4g0v0_Cancun' panicked at /Users/msaug/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-ec-0.4.2/src/models/short_weierstrass/affine.rs:77:9:
assertion failed: point.is_on_curve()

thread 'stPreCompiledContracts2::test_CallEcrecover_Overflow_d4g0v0_Cancun' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
```

```
   0:        0x10e82e74c - std::backtrace_rs::backtrace::libunwind::trace::hbebc8679d47bdc2c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x10e82e74c - std::backtrace_rs::backtrace::trace_unsynchronized::h3a2e9637943241aa
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10e82e74c - std::sys::backtrace::_print_fmt::he430849680584674
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:        0x10e82e74c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:        0x10e84b5ec - core::fmt::rt::Argument::fmt::h0d339881c25f3c31
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:        0x10e84b5ec - core::fmt::write::hb3cfb8a30e72d7ff
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:        0x10e82b9e4 - std::io::Write::write_fmt::hfb2314975de9ecf1
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:        0x10e82fc74 - std::sys::backtrace::BacktraceLock::print::he14461129ccbfef5
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:        0x10e82fc74 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:        0x10e82f898 - std::panicking::default_hook::hc62e60da3be2f352
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:        0x10e830738 - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:        0x10e830060 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:667:13
  12:        0x10e82ebd8 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:        0x10e82fd50 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:        0x10ece17ac - core::panicking::panic_nounwind_fmt::runtime::h5290ab2b4897aadc
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:112:18
  15:        0x10ece17ac - core::panicking::panic_nounwind_fmt::h91ee161184879b56
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:122:5
  16:        0x10ece1824 - core::panicking::panic_nounwind::heab7ebe7a6cd845c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:221:5
  17:        0x10ece1954 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:309:5
  18:        0x104943108 - cairo_native::starknet::handler::StarknetSyscallHandlerCallbacks<T>::wrap_secp256k1_add::hc2142a54f1359a37
                               at /Users/msaug/.cargo/git/checkouts/cairo_native-0bad8506281b7281/f3f6ba2/src/starknet.rs:1476:9
  19:        0x12f7eeebc - _impl$core::starknet::secp256_trait::recover_public_key::<core::starknet::secp256k1::Secp256k1Point, core::starknet::secp256k1::Secp256k1PointDrop, core::starknet::secp256k1::Secp256k1Impl, core::starknet::secp256k1::Secp256k1PointImpl>(f276)
  20:        0x12f7be184 - _impl$evm::precompiles::ec_recover::EcRecover::exec(f240)
  21:        0x12f3eaa04 - _impl$evm::precompiles::PrecompilesImpl::exec_precompile(f134)
  22:        0x12f216f90 - _impl$evm::interpreter::EVMImpl::execute_code(f109)
  23:        0x12f1def10 - _impl$evm::interpreter::EVMImpl::process_message(f79)
  24:        0x12f7d344c - _impl$evm::call_helpers::CallHelpersImpl::generic_call(f254)
  25:        0x12f4d3314 - _impl$evm::instructions::system_operations::SystemOperations::exec_call(f152)
  26:        0x12f346610 - _impl$evm::interpreter::EVMImpl::execute_opcode(f133)
  27:        0x12f210978 - _impl$evm::interpreter::EVMImpl::execute_code(f109)
  28:        0x12f1def10 - _impl$evm::interpreter::EVMImpl::process_message(f79)
  29:        0x12f1babfc - _impl$evm::interpreter::EVMImpl::process_message_call(f61)
  30:        0x12f1a1288 - _impl$evm::interpreter::EVMImpl::process_transaction(f47)
  31:        0x12f18ba04 - _impl$contracts::kakarot_core::eth_rpc::EthRPC::<contracts::kakarot_core::kakarot::KakarotCore::ContractState, contracts::kakarot_core::kakarot::KakarotCore::_KakarotCoreState, contracts::kakarot_core::kakarot::KakarotCore::ContractStateDrop>::eth_send_transaction(f38)
  32:        0x12f180b5c - _impl$contracts::kakarot_core::eth_rpc::__wrapper__EthRPC__eth_send_transaction::<contracts::kakarot_core::kakarot::KakarotCore::ContractState, contracts::kakarot_core::kakarot::KakarotCore::_KakarotCoreState, contracts::kakarot_core::kakarot::KakarotCore::ContractStateDrop, contracts::kakarot_core::kakarot::KakarotCore::ContractStateEthRPC>(f23)
  33:        0x12f181388 - __mlir_ciface_f23
thread caused non-unwinding panic. aborting.
```

Repro:
scarb 2.8.3
clone https://github.com/kkrt-labs/kakarot-ssj on main
`scarb build -p contracts` - builds the required contract with some debug print logs

clone https://github.com/kkrt-labs/ef-tests
ensure correct branch `git checkout feat/cairo-native`
`make`
`make setup-kakarot`
copy the contracts built previously:`cp ../kakarot-ssj/target/dev/contracts_* build/v1`
`cargo test test_CallEcrecover_Overflow_d0g0v0_Cancun --features v1,native -- --nocapture`

**Comment by enitrat** [comment]
```rust
    /// Constructs a group element from x and y coordinates.
    /// Performs checks to ensure that the point is on the curve and is in the right subgroup.
    pub fn new(x: P::BaseField, y: P::BaseField) -> Self {
        let point = Self {
            x,
            y,
            infinity: false,
        };
        assert!(point.is_on_curve());
        assert!(point.is_in_correct_subgroup_assuming_on_curve());
        point
    }
 ```
 
This is the source code for `ark-ec-0.4.2/src/models/short_weierstrass/affine.rs:77:9`
 Looks like the panic happens when we try to create a group element from x, y that are not on the curve. 

test data=4, which corresponds to a test with`# S Overflow == secp256k1N`
The test data is defined as:

```yml
# Test limit RS values for EC Recover precompile (R, S == secp256k1n)
# secp256k1n == 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141

CallEcrecover_Overflow:

  env:
    currentCoinbase: 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba
    currentDifficulty: '0x20000'
    currentGasLimit: '0xFF112233445566'
    currentNumber: '1'
    currentTimestamp: '1000'

  pre:  


    cccccccccccccccccccccccccccccccccccccccc:
      code: |
        :yul berlin
        {
         // Copy Hash, V, R, S values
         calldatacopy(0x00, 0x04, 0x80)

         // Call the EC Recover Precompile
         sstore(0, call(3000, 1, 0, 0, 0x80, 0x80, 0x20))
         sstore(1, mload(0x80))
        }  
      nonce: '0'
      storage: {}
      balance: 0



    a94f5374fce5edbc8e2a8697c15331677e6ebf0b:
      balance: '1000000000000000000'
      code: 0x
      nonce: '0'
      storage: {}


  transaction:
    data:
    # R Overflow == secp256k1N
    - :label fail     :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141 0x1fffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804
    # R Overflow == secp256k1N + 1
    - :label fail     :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142 0x1fffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804
    # R High == secp256k1N - 1 (Fails due to R not being able to be a point on the curve, not due to the secp256k1N limit)
    - :label fail     :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140 0xefffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804
    # R High == secp256k1N - 2
    - :label pass01   :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f 0xefffd310ac743f371de3b9f7f9cb56c0b28ad43601b4ab949f53faa07bd2c804
    # S Overflow == secp256k1N
    - :label fail     :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0x48b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141
    # S Overflow == secp256k1N + 1
    - :label fail     :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0x48b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142
    # S High == secp256k1N - 1
    - :label pass02   :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0x48b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140
    # S High == secp256k1N - 2
    - :label pass03   :abi f(uint,uint,uint,uint) 0x18c547e4f7b0f325ad1e56f57e26c745b09a3e503d86e00e5255ff7f715d3d1c 0x1c 0x48b55bfa915ac795c431978d8a6a992b628d557da5ff759b307d495a36649353 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f

    gasLimit:
    - 'F000000000'
    gasPrice: '10'
    nonce: '0'
    secretKey: 45a915e4d060149eb4365960e6a7a45f334393093061116b197e3240065ff2d8
    to: cccccccccccccccccccccccccccccccccccccccc

    value:
    - '100000'



  expect:

  - indexes:
      data: 
      - :label fail
      gas: !!int -1
      value: !!int -1
    network: 
    - ">=Cancun"
    result:
      cccccccccccccccccccccccccccccccccccccccc:
        storage:
          0x00: 0x01
          0x01: 0x00

  - indexes:
      data: 
      - :label pass01
      gas: !!int -1
      value: !!int -1
    network: 
    - ">=Cancun"
    result:
      cccccccccccccccccccccccccccccccccccccccc:
        storage:
          0x00: 0x01
          0x01: 0x2182da748249a933bf737586b80212df19b8f829

  - indexes:
      data: 
      - :label pass02
      gas: !!int -1
      value: !!int -1
    network: 
    - ">=Cancun"
    result:
      cccccccccccccccccccccccccccccccccccccccc:
        storage:
          0x00: 0x01
          0x01: 0x1b85ac3c9b09de43659c5d04a2d9c75457d9abf4

  - indexes:
      data: 
      - :label pass03
      gas: !!int -1
      value: !!int -1
    network: 
    - ">=Cancun"
    result:
      cccccccccccccccccccccccccccccccccccccccc:
        storage:
          0x00: 0x01
          0x01: 0xd0277c8a3eccd462a313fc60161bac36b16e8699
```

I think the crate used to 'translate' cairo's `recover_public_key` doesn't have strictly the same behavior and panics if S is not the right value?
